# Generated by Django 5.0.4 on 2025-05-06 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MakePi', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toilette',
            name='arrondissement',
            field=models.CharField(blank=True, max_length=5),
        ),
    ]
