# Generated by Django 5.0.4 on 2025-05-03 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Toilette',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(blank=True, max_length=100)),
                ('adresse', models.TextField(blank=True)),
                ('arrondissement', models.CharField(blank=True, max_length=2)),
                ('horaires', models.CharField(blank=True, max_length=255)),
                ('acces_pmr', models.BooleanField(default=False)),
                ('relais_bebe', models.BooleanField(default=False)),
                ('latitude', models.FloatField(blank=True, null=True)),
                ('longitude', models.FloatField(blank=True, null=True)),
            ],
        ),
    ]
